<script setup lang="ts">
import { computed, ref } from 'vue'
const props = defineProps<{ locale: 'zh' | 'en' }>()
const en = props.locale === 'en'; const base = import.meta.env.BASE_URL.replace(/\/$/, ''); const prefix = en ? `${base}/en` : base; const sitePath = (path: string) => `${base}${path.endsWith('/') ? path : `${path}.html`}`; const activeTag = ref('')
const posts = en ? [
  ['2026-08-19','One Month Into Security: The Three Lessons That Mattered Most','An essay: from SQL injection to my first XSS payload, from launching this blog to building a WeChat bot.',['Essay','Learning'],'first-month-essay'],['2026-08-19','Putting an AI in a WeChat Group: Screenshots, OCR, and Coordinate Clicks','A project retrospective about screenshots, OCR and Win32 messages.',['Projects','Python','Automation'],'wechat-bot'],['2026-08-17','Hello, World',"The first post on Koki's blog — how this site was built and what to expect here.",['Misc','Next.js'],'hello-world'],['2026-08-17','SQL Injection 101: It Starts With One Quote','Your first web security lesson and why parameterized queries stop injection.',['Security','Web Security'],'sql-injection'],['2026-08-16','CTF Is Not Hacking — It\'s Puzzle-Solving','What CTF is, its categories, and how to start from absolute zero.',['Security','CTF'],'ctf-intro'],['2026-08-15','Cryptography 101: From Caesar to HTTPS','The core concepts of cryptography, explained.',['Security','Cryptography'],'crypto-intro'],['2026-08-13','The Security Toolkit: Your First Gear, From Zero','A beginner equipment list for information security.',['Security','Tools'],'security-toolkit'],['2026-08-12','From Zero to Hero: The Complete Security Learning Map','A six-stage learning map for information security.',['Security','Learning Path'],'security-roadmap-full'],['2026-08-10','Markdown Writing Guide','A sample post demonstrating every formatting style.',['Tutorial','Markdown'],'markdown-guide'],['2026-08-19','XSS 101: Why Your Browser Executes Other People\'s Code','What XSS is and why escaping stops it.',['Security','Web Security'],'xss-intro'],
] : [
  ['2026-08-19','学安全一个月，我最大的三句心得','从 SQL 注入到第一条 XSS payload，从搭博客到写微信机器人。',['随笔','学习'],'first-month-essay'],['2026-08-19','把一个 AI 塞进微信群：截图 + OCR + 坐标点击的野路子自动化','用截图、OCR 和 Win32 消息给微信群做一个 AI 助手。',['项目','Python','自动化'],'wechat-bot'],['2026-08-17','你好，世界','Koki 博客的第一篇文章，聊聊这个网站是怎么搭起来的。',['随笔','Next.js'],'hello-world'],['2026-08-17','SQL 注入入门：从一条引号开始',"什么是 SQL 注入、' OR '1'='1 如何绕过验证，以及参数化查询为何有效。",['安全','Web安全'],'sql-injection'],['2026-08-16','CTF 不是黑客，是解谜游戏','信息安全入门的最佳姿势：CTF 是什么以及怎么开始玩。',['安全','CTF'],'ctf-intro'],['2026-08-15','密码学入门：从凯撒密码到 HTTPS','密码学的核心概念一次讲清楚。',['安全','密码学'],'crypto-intro'],['2026-08-13','安全学习工具包：从零配置你的第一套装备','信息安全新手的装备清单。',['安全','工具'],'security-toolkit'],['2026-08-12','从入门到入土：信息安全学习全景图','六个阶段的完整学习地图。',['安全','学习路线'],'security-roadmap-full'],['2026-08-10','Markdown 写作示例','演示各种排版效果的示例文章。',['教程','Markdown'],'markdown-guide'],['2026-08-19','XSS 入门：浏览器为什么会执行别人的代码','XSS 是什么、不同类型和防护方式。',['安全','Web安全'],'xss-intro'],
]
const tags = computed(() => [...new Set(posts.flatMap((p) => p[3] as string[]))])
const filtered = computed(() => activeTag.value ? posts.filter((p) => (p[3] as string[]).includes(activeTag.value)) : posts)
const postTags = (post: (string | string[])[]) => post[3] as string[]
</script>
<template><main class="blog-replica"><div class="blog-heading"><div><h1>{{ en ? 'Blog' : '博客' }}</h1><p>{{ en ? 'Articles about technology, tools and life.' : '关于技术、工具与生活的文章。' }}</p></div><a :href="sitePath(en ? '/en/archive' : '/archive')">{{ en ? 'Archive →' : '按年份归档 →' }}</a></div><div class="blog-tags"><button :class="{active: !activeTag}" @click="activeTag=''">{{ en ? 'All' : '全部' }}</button><button v-for="tag in tags" :key="tag" :class="{active: activeTag === tag}" @click="activeTag=tag">{{ tag }}</button></div><div class="blog-list"><a v-for="p in filtered" :key="p[4]" class="blog-card" :href="sitePath(`${en ? '/en' : ''}/blog/${p[4]}`)"><div class="blog-meta"><time>{{ p[0] }}</time><span v-for="tag in postTags(p)" :key="tag">{{ tag }}</span></div><h2>{{ p[1] }}</h2><p>{{ p[2] }}</p></a></div></main></template>
