<script setup lang="ts">
import { getCarsContent } from '../../data/cars'
import { getPhysicsContent } from '../../data/physics'
import { getSecurityContent } from '../../data/security'
const props = defineProps<{ kind: 'security' | 'cars' | 'physics'; locale: 'zh' | 'en' }>()
const cars = getCarsContent(props.locale); const physics = getPhysicsContent(props.locale); const security = getSecurityContent(props.locale)
</script>
<template>
  <section v-if="kind === 'cars'" class="full-data"><article v-for="topic in cars.topics" :id="topic.key" :key="topic.key" class="lab-article"><h3>{{ topic.icon }} {{ topic.title }}</h3><p v-for="paragraph in topic.paragraphs" :key="paragraph" class="lab-prose">{{ paragraph }}</p><ul><li v-for="point in topic.points" :key="point">{{ point }}</li></ul></article><h2>📇 {{ locale === 'en' ? 'Terms' : '术语表' }}</h2><div class="lab-grid"><article v-for="term in cars.terms" :key="term.term" class="lab-card"><h3>{{ term.term }}</h3><p>{{ term.definition }}</p></article></div></section>
  <section v-else-if="kind === 'physics'" class="full-data"><article v-for="topic in physics.topics" :id="topic.key" :key="topic.key" class="lab-article"><h3>{{ topic.icon }} {{ topic.title }}</h3><p v-for="paragraph in topic.paragraphs" :key="paragraph" class="lab-prose">{{ paragraph }}</p><ul><li v-for="point in topic.points" :key="point">{{ point }}</li></ul></article><h2>🏢 {{ locale === 'en' ? 'Brands' : '品牌' }}</h2><article v-for="brand in physics.brands" :key="brand.name" class="lab-article"><h3>{{ brand.icon }} {{ brand.name }} <small>{{ brand.origin }}</small></h3><p>{{ brand.description }}</p><p class="muted">{{ brand.strengths.join(' · ') }}</p></article><h2>📇 {{ locale === 'en' ? 'Terms' : '术语表' }}</h2><div class="lab-grid"><article v-for="term in physics.terms" :key="term.term" class="lab-card"><h3>{{ term.term }}</h3><p>{{ term.definition }}</p></article></div></section>
  <section v-else class="full-data"><article v-for="stage in security.stages" :key="stage.key" class="lab-article"><h3>{{ stage.title }} <small>{{ stage.duration }}</small></h3><p><strong>{{ locale === 'en' ? 'Learn' : '学什么' }}：</strong>{{ stage.learn.join(' · ') }}</p><p><strong>{{ locale === 'en' ? 'Practice' : '练什么' }}：</strong>{{ stage.practice.join(' · ') }}</p><p><strong>{{ locale === 'en' ? 'Milestone' : '过关标准' }}：</strong>{{ stage.milestone }}</p></article><h2>🎯 {{ locale === 'en' ? 'Platforms and toolkit' : '平台与工具包' }}</h2><div class="lab-grid"><a v-for="item in security.platforms" :key="item.title" class="lab-card" :href="item.url" target="_blank"><h3>{{ item.title }}</h3><p>{{ item.description }}</p><small>{{ item.tag }}</small></a><a v-for="item in security.tools" :key="item.name" class="lab-card" :href="item.url" target="_blank"><h3>{{ item.name }}</h3><p>{{ item.description }}</p><small>{{ item.category }}</small></a></div><h2>📋 {{ locale === 'en' ? 'Cheatsheets' : '速查表' }}</h2><article v-for="sheet in security.cheats" :key="sheet.title" class="lab-article"><h3>{{ sheet.title }}</h3><dl><div v-for="row in sheet.rows" :key="row.item"><dt>{{ row.item }}</dt><dd>{{ row.usage }}</dd></div></dl></article></section>
</template>
