<script setup lang="ts">
import { computed, ref } from 'vue'
import { getRoadmap } from '../../data/roadmaps'
import { getResourceCategories } from '../../data/resources'
import { getBooks } from '../../data/books'
import { getFriends } from '../../data/friends'
const props = defineProps<{ kind: 'roadmap' | 'resources' | 'books' | 'archive' | 'friends' | 'guestbook'; locale: 'zh' | 'en' }>()
const en = props.locale === 'en'; const base = import.meta.env.BASE_URL.replace(/\/$/, ''); const sitePath = (path: string) => `${base}${path.endsWith('/') ? path : `${path}.html`}`
const roadmap = getRoadmap(props.locale); const resources = getResourceCategories(props.locale); const books = getBooks(props.locale); const friends = getFriends()
const activeType = ref(''); const activeLevel = ref(''); const guestName = ref(''); const guestMessage = ref(''); const submitted = ref(false)
const resourceItems = computed(() => resources.flatMap((category) => category.resources.map((resource) => ({ ...resource, category: category.title }))).filter((r) => (!activeType.value || r.type === activeType.value) && (!activeLevel.value || r.level === activeLevel.value)))
const posts = en ? [['2026-08-19','One Month Into Security: The Three Lessons That Mattered Most','first-month-essay'],['2026-08-19','Putting an AI in a WeChat Group: Screenshots, OCR, and Coordinate Clicks','wechat-bot'],['2026-08-17','Hello, World','hello-world'],['2026-08-17','SQL Injection 101: It Starts With One Quote','sql-injection'],['2026-08-16','CTF Is Not Hacking — It\'s Puzzle-Solving','ctf-intro'],['2026-08-15','Cryptography 101: From Caesar to HTTPS','crypto-intro'],['2026-08-13','The Security Toolkit: Your First Gear, From Zero','security-toolkit'],['2026-08-12','From Zero to Hero: The Complete Security Learning Map','security-roadmap-full'],['2026-08-10','Markdown Writing Guide','markdown-guide'],['2026-08-19','XSS 101: Why Your Browser Executes Other People\'s Code','xss-intro']] : [['2026-08-19','学安全一个月，我最大的三句心得','first-month-essay'],['2026-08-19','把一个 AI 塞进微信群：截图 + OCR + 坐标点击的野路子自动化','wechat-bot'],['2026-08-17','你好，世界','hello-world'],['2026-08-17','SQL 注入入门：从一条引号开始','sql-injection'],['2026-08-16','CTF 不是黑客，是解谜游戏','ctf-intro'],['2026-08-15','密码学入门：从凯撒密码到 HTTPS','crypto-intro'],['2026-08-13','安全学习工具包：从零配置你的第一套装备','security-toolkit'],['2026-08-12','从入门到入土：信息安全学习全景图','security-roadmap-full'],['2026-08-10','Markdown 写作示例','markdown-guide'],['2026-08-19','XSS 入门：浏览器为什么会执行别人的代码','xss-intro']]
function submitGuestbook() { if (guestName.value.trim() && guestMessage.value.trim()) submitted.value = true }
</script>
<template>
  <main class="learning-replica">
    <template v-if="kind === 'roadmap'"><header class="learning-heading"><h1>{{ en ? 'Learning Roadmap' : '学习路线' }}</h1><p>{{ en ? 'A practical path from programming basics to independent security research.' : '从零开始学编程的路线图：每一步该学什么、用什么资源、花多少时间。' }}</p><a :href="sitePath(en ? '/en/resources' : '/resources')">{{ en ? 'Supporting resources →' : '配套资料见「资料」页 →' }}</a></header><nav class="learning-tabs"><a v-for="track in roadmap.tracks" :key="track.key" :href="`#${track.key}`">{{ track.title }}</a><a href="#tips">💡 Tips</a></nav><section v-for="track in roadmap.tracks" :id="track.key" :key="track.key" class="roadmap-track"><h2>{{ track.title }}</h2><p class="muted">{{ track.goal }}</p><ol class="timeline"><li v-for="(step,index) in track.steps" :key="step.title"><span>{{ index+1 }}</span><div><h3>{{ step.title }} <small>{{ step.duration }}</small></h3><p>{{ step.description }}</p></div></li></ol></section><section id="tips" class="roadmap-track"><h2>💡 {{ en ? 'General tips' : '通用建议' }}</h2><ul class="tip-list"><li v-for="tip in roadmap.tips" :key="tip">{{ tip }}</li></ul></section></template>
    <template v-else-if="kind === 'resources'"><header class="learning-heading"><h1>{{ en ? 'Resources' : '学习资料' }}</h1><p>{{ en ? 'Free-first tutorials, videos, books and practice platforms.' : '从零开始学编程的精选资源：教程、视频、书籍与刷题平台，全部免费为主，小白好上手。' }}</p></header><div class="resource-filters"><button :class="{active:!activeType}" @click="activeType=''">{{ en ? 'All' : '全部' }}</button><button v-for="type in ['website','video','book','course','practice']" :key="type" :class="{active:activeType===type}" @click="activeType=type">{{ type }}</button><button v-for="level in ['beginner','intermediate','reference']" :key="level" :class="{active:activeLevel===level}" @click="activeLevel=activeLevel===level?'':level">{{ level }}</button></div><section v-for="category in resources" :id="category.key" :key="category.key" class="resource-category"><h2>{{ category.title }}</h2><p class="muted">{{ category.description }}</p><div class="resource-grid"><a v-for="resource in resourceItems.filter(r=>r.category===category.title)" :key="resource.url" class="resource-card" :href="resource.url" target="_blank"><div><span class="badge">{{ resource.type }}</span><span class="level">{{ resource.level }}</span><span class="stars">{{ '★'.repeat(resource.rating) }}</span></div><h3>{{ resource.title }}</h3><p>{{ resource.description }}</p></a></div></section></template>
    <template v-else-if="kind === 'books'"><header class="learning-heading"><h1>{{ en ? 'Books' : '书单' }}</h1><p>{{ en ? 'Reading, finished and wish-list books with short notes.' : '在读的、读完的、想读的书，附上简短笔记。' }}</p></header><section v-for="status in ['reading','finished','want']" :key="status" class="book-section"><h2>{{ status }} · {{ books.filter(b=>b.status===status).length }}</h2><div class="book-list"><article v-for="book in books.filter(b=>b.status===status)" :key="book.title" class="book-card"><div class="book-head"><h3>{{ book.title }}</h3><span v-if="book.rating" class="stars">{{ '★'.repeat(book.rating) }}{{ '☆'.repeat(5-book.rating) }}</span></div><small>{{ book.author }}</small><p>{{ book.note }}</p></article></div></section></template>
    <template v-else-if="kind === 'archive'"><header class="learning-heading"><a :href="sitePath(en ? '/en/blog/' : '/blog/')">← {{ en ? 'Back to blog' : '返回博客' }}</a><h1>{{ en ? 'Archive' : '文章归档' }}</h1><p>{{ en ? 'All posts grouped by year.' : '按年份归档的全部文章。' }}</p></header><section class="archive-year"><h2>2026 · {{ posts.length }}</h2><a v-for="post in posts" :key="post[2]" class="archive-row" :href="sitePath(`${en ? '/en' : ''}/blog/${post[2]}`)"><time>{{ post[0] }}</time><span>{{ post[1] }}</span></a></section></template>
    <template v-else-if="kind === 'friends'"><header class="learning-heading"><h1>{{ en ? 'Friends' : '友链' }}</h1><p>{{ en ? 'Personal sites and communities worth following.' : '值得长期阅读的个人网站与社区。' }}</p></header><div v-if="friends.length" class="resource-grid"><a v-for="friend in friends" :key="friend.url" class="resource-card" :href="friend.url" target="_blank"><h3>{{ friend.emoji }} {{ friend.name }}</h3><p>{{ friend.description }}</p></a></div><p v-else class="empty-state">{{ en ? 'No links yet. Contact me on GitHub to apply.' : '友链正在整理中，欢迎通过 GitHub 联系我。' }}</p><div class="apply-card"><h2>{{ en ? 'Apply for a link' : '申请友链' }}</h2><p>{{ en ? 'Send your site name, URL and a short introduction by email.' : '请通过邮件发送站点名称、链接和一句话介绍。' }} <a href="mailto:3210254261@qq.com">3210254261@qq.com</a></p></div></template>
    <template v-else><header class="learning-heading"><h1>{{ en ? 'Guestbook' : '留言板' }}</h1><p>{{ en ? 'Leave a thought, suggestion or hello.' : '留下你的想法、建议或一句问候。' }}</p></header><form class="guestbook-form" @submit.prevent="submitGuestbook"><label>{{ en ? 'Name' : '昵称' }}<input v-model="guestName" required></label><label>{{ en ? 'Message' : '留言' }}<textarea v-model="guestMessage" rows="5" required></textarea></label><button type="submit">{{ en ? 'Submit' : '提交留言' }}</button><p class="muted">{{ submitted ? (en ? 'Static mode: message was not sent.' : '当前为静态模式，留言未发送。') : (en ? 'Remote API is not configured; no fake success is shown.' : '远程 API 未配置，不会伪造提交成功。') }}</p></form><section class="guestbook-list"><h2>{{ en ? 'Messages (0)' : '留言列表（0）' }}</h2><p class="empty-state">{{ en ? 'No messages yet.' : '还没有留言。' }}</p></section></template>
  </main>
</template>
